defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome69

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install NPM dependencies
          command: npm ci
      - run:
          name: Verify Cypress
          command: npm run cypress-verify
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress

  code-style:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Check code style
          command: npm run style

  unit-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Perform unit tests and send coverage data
          command: npm run jest-tests-with-coverage

  browser-integration-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run browser integration tests and record data
          command: npx start-server-and-test develop http://localhost:8000 cypress-run-record

workflows:
  version: 2
  run-tests:
    jobs:
      - build
      - code-style:
          requires:
            - build
      - unit-tests:
          requires:
            - build
            - code-style
      - browser-integration-tests:
          requires:
            - build
            - unit-tests
